export const ErrorCode = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  TICKET_NOT_FOUND: "TICKET_NOT_FOUND",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  INVALID_STATUS_TRANSITION: "INVALID_STATUS_TRANSITION",
  INVALID_PRIORITY: "INVALID_PRIORITY",
  INVALID_COMMENT: "INVALID_COMMENT",
  INVALID_ROLE: "INVALID_ROLE",
  EMAIL_TAKEN: "EMAIL_TAKEN",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
} as const;

export type ErrorCodeName = (typeof ErrorCode)[keyof typeof ErrorCode];
